	ori.b	#$FF,ccr
	ori	#$FF,ccr
	ori.w	#$FFFF,sr
	ori	#$FFFF,sr
	ori.b	#$FF,d5
	ori.b	#$FF,(a2)
	ori.b	#$FF,(a2)+
	ori.b	#$FF,-(a2)
	ori.b	#$FF,$7FFF(a2)
	ori.b	#$FF,$7F(a2,d5.w)
	ori.b	#$FF,($FFFFFFFF).w
	ori.b	#$FF,($FFFFFFFF).l
	ori.w	#$FFFF,d5
	ori.w	#$FFFF,(a2)
	ori.w	#$FFFF,(a2)+
	ori.w	#$FFFF,-(a2)
	ori.w	#$FFFF,$7FFF(a2)
	ori.w	#$FFFF,$7F(a2,d5.w)
	ori.w	#$FFFF,($FFFFFFFF).w
	ori.w	#$FFFF,($FFFFFFFF).l
	ori.l	#$FFFFFFFF,d5
	ori.l	#$FFFFFFFF,(a2)
	ori.l	#$FFFFFFFF,(a2)+
	ori.l	#$FFFFFFFF,-(a2)
	ori.l	#$FFFFFFFF,$7FFF(a2)
	ori.l	#$FFFFFFFF,$7F(a2,d5.w)
	ori.l	#$FFFFFFFF,($FFFFFFFF).w
	ori.l	#$FFFFFFFF,($FFFFFFFF).l

	andi.b	#$FF,ccr
	andi	#$FF,ccr
	andi.w	#$FFFF,sr
	andi	#$FFFF,sr
	andi.b	#$FF,d5
	andi.b	#$FF,(a2)
	andi.b	#$FF,(a2)+
	andi.b	#$FF,-(a2)
	andi.b	#$FF,$7FFF(a2)
	andi.b	#$FF,$7F(a2,d5.w)
	andi.b	#$FF,($FFFFFFFF).w
	andi.b	#$FF,($FFFFFFFF).l
	andi.w	#$FFFF,d5
	andi.w	#$FFFF,(a2)
	andi.w	#$FFFF,(a2)+
	andi.w	#$FFFF,-(a2)
	andi.w	#$FFFF,$7FFF(a2)
	andi.w	#$FFFF,$7F(a2,d5.w)
	andi.w	#$FFFF,($FFFFFFFF).w
	andi.w	#$FFFF,($FFFFFFFF).l
	andi.l	#$FFFFFFFF,d5
	andi.l	#$FFFFFFFF,(a2)
	andi.l	#$FFFFFFFF,(a2)+
	andi.l	#$FFFFFFFF,-(a2)
	andi.l	#$FFFFFFFF,$7FFF(a2)
	andi.l	#$FFFFFFFF,$7F(a2,d5.w)
	andi.l	#$FFFFFFFF,($FFFFFFFF).w
	andi.l	#$FFFFFFFF,($FFFFFFFF).l

	subi.b	#$FF,d5
	subi.b	#$FF,(a2)
	subi.b	#$FF,(a2)+
	subi.b	#$FF,-(a2)
	subi.b	#$FF,$7FFF(a2)
	subi.b	#$FF,$7F(a2,d5.w)
	subi.b	#$FF,($FFFFFFFF).w
	subi.b	#$FF,($FFFFFFFF).l
	subi.w	#$FFFF,d5
	subi.w	#$FFFF,(a2)
	subi.w	#$FFFF,(a2)+
	subi.w	#$FFFF,-(a2)
	subi.w	#$FFFF,$7FFF(a2)
	subi.w	#$FFFF,$7F(a2,d5.w)
	subi.w	#$FFFF,($FFFFFFFF).w
	subi.w	#$FFFF,($FFFFFFFF).l
	subi.l	#$FFFFFFFF,d5
	subi.l	#$FFFFFFFF,(a2)
	subi.l	#$FFFFFFFF,(a2)+
	subi.l	#$FFFFFFFF,-(a2)
	subi.l	#$FFFFFFFF,$7FFF(a2)
	subi.l	#$FFFFFFFF,$7F(a2,d5.w)
	subi.l	#$FFFFFFFF,($FFFFFFFF).w
	subi.l	#$FFFFFFFF,($FFFFFFFF).l

	addi.b	#$FF,d5
	addi.b	#$FF,(a2)
	addi.b	#$FF,(a2)+
	addi.b	#$FF,-(a2)
	addi.b	#$FF,$7FFF(a2)
	addi.b	#$FF,$7F(a2,d5.w)
	addi.b	#$FF,($FFFFFFFF).w
	addi.b	#$FF,($FFFFFFFF).l
	addi.w	#$FFFF,d5
	addi.w	#$FFFF,(a2)
	addi.w	#$FFFF,(a2)+
	addi.w	#$FFFF,-(a2)
	addi.w	#$FFFF,$7FFF(a2)
	addi.w	#$FFFF,$7F(a2,d5.w)
	addi.w	#$FFFF,($FFFFFFFF).w
	addi.w	#$FFFF,($FFFFFFFF).l
	addi.l	#$FFFFFFFF,d5
	addi.l	#$FFFFFFFF,(a2)
	addi.l	#$FFFFFFFF,(a2)+
	addi.l	#$FFFFFFFF,-(a2)
	addi.l	#$FFFFFFFF,$7FFF(a2)
	addi.l	#$FFFFFFFF,$7F(a2,d5.w)
	addi.l	#$FFFFFFFF,($FFFFFFFF).w
	addi.l	#$FFFFFFFF,($FFFFFFFF).l

	eori.b	#$FF,ccr
	eori	#$FF,ccr
	eori.w	#$FFFF,sr
	eori	#$FFFF,sr
	eori.b	#$FF,d5
	eori.b	#$FF,(a2)
	eori.b	#$FF,(a2)+
	eori.b	#$FF,-(a2)
	eori.b	#$FF,$7FFF(a2)
	eori.b	#$FF,$7F(a2,d5.w)
	eori.b	#$FF,($FFFFFFFF).w
	eori.b	#$FF,($FFFFFFFF).l
	eori.w	#$FFFF,d5
	eori.w	#$FFFF,(a2)
	eori.w	#$FFFF,(a2)+
	eori.w	#$FFFF,-(a2)
	eori.w	#$FFFF,$7FFF(a2)
	eori.w	#$FFFF,$7F(a2,d5.w)
	eori.w	#$FFFF,($FFFFFFFF).w
	eori.w	#$FFFF,($FFFFFFFF).l
	eori.l	#$FFFFFFFF,d5
	eori.l	#$FFFFFFFF,(a2)
	eori.l	#$FFFFFFFF,(a2)+
	eori.l	#$FFFFFFFF,-(a2)
	eori.l	#$FFFFFFFF,$7FFF(a2)
	eori.l	#$FFFFFFFF,$7F(a2,d5.w)
	eori.l	#$FFFFFFFF,($FFFFFFFF).w
	eori.l	#$FFFFFFFF,($FFFFFFFF).l

	cmpi.b	#$FF,d5
	cmpi.b	#$FF,(a2)
	cmpi.b	#$FF,(a2)+
	cmpi.b	#$FF,-(a2)
	cmpi.b	#$FF,$7FFF(a2)
	cmpi.b	#$FF,$7F(a2,d5.w)
	cmpi.b	#$FF,($FFFFFFFF).w
	cmpi.b	#$FF,($FFFFFFFF).l
	cmpi.w	#$FFFF,d5
	cmpi.w	#$FFFF,(a2)
	cmpi.w	#$FFFF,(a2)+
	cmpi.w	#$FFFF,-(a2)
	cmpi.w	#$FFFF,$7FFF(a2)
	cmpi.w	#$FFFF,$7F(a2,d5.w)
	cmpi.w	#$FFFF,($FFFFFFFF).w
	cmpi.w	#$FFFF,($FFFFFFFF).l
	cmpi.l	#$FFFFFFFF,d5
	cmpi.l	#$FFFFFFFF,(a2)
	cmpi.l	#$FFFFFFFF,(a2)+
	cmpi.l	#$FFFFFFFF,-(a2)
	cmpi.l	#$FFFFFFFF,$7FFF(a2)
	cmpi.l	#$FFFFFFFF,$7F(a2,d5.w)
	cmpi.l	#$FFFFFFFF,($FFFFFFFF).w
	cmpi.l	#$FFFFFFFF,($FFFFFFFF).l

	btst.l	d2,d5
	btst.b	d5,(a2)
	btst.b	d5,(a2)+
	btst.b	d5,-(a2)
	btst.b	d5,$7FFF(a2)
	btst.b	d5,$7F(a2,d5.w)
	btst.b	d5,($FFFFFFFF).w
	btst.b	d5,($FFFFFFFF).l
	btst.b	d5,#$55
	btst.b	d5,*(pc)
	btst.b	d5,*(pc,d5.w)

	btst	d2,d5
	btst	d5,(a2)
	btst	d5,(a2)+
	btst	d5,-(a2)
	btst	d5,$7FFF(a2)
	btst	d5,$7F(a2,d5.w)
	btst	d5,($FFFFFFFF).w
	btst	d5,($FFFFFFFF).l
	btst	d5,#$55
	btst	d5,*(pc)
	btst	d5,*(pc,d5.w)

	btst.l	#0,d5
	btst.b	#0,(a2)
	btst.b	#0,(a2)+
	btst.b	#0,-(a2)
	btst.b	#0,$7FFF(a2)
	btst.b	#0,$7F(a2,d5.w)
	btst.b	#0,($FFFFFFFF).w
	btst.b	#0,($FFFFFFFF).l
	btst.b	#0,*(pc)
	btst.b	#0,*(pc,d5.w)

	btst	#0,d5
	btst	#0,(a2)
	btst	#0,(a2)+
	btst	#0,-(a2)
	btst	#0,$7FFF(a2)
	btst	#0,$7F(a2,d5.w)
	btst	#0,($FFFFFFFF).w
	btst	#0,($FFFFFFFF).l
	btst	#0,*(pc)
	btst	#0,*(pc,d5.w)

	bchg.l	d2,d5
	bchg.b	d5,(a2)
	bchg.b	d5,(a2)+
	bchg.b	d5,-(a2)
	bchg.b	d5,$7FFF(a2)
	bchg.b	d5,$7F(a2,d5.w)
	bchg.b	d5,($FFFFFFFF).w
	bchg.b	d5,($FFFFFFFF).l

	bchg	d2,d5
	bchg	d5,(a2)
	bchg	d5,(a2)+
	bchg	d5,-(a2)
	bchg	d5,$7FFF(a2)
	bchg	d5,$7F(a2,d5.w)
	bchg	d5,($FFFFFFFF).w
	bchg	d5,($FFFFFFFF).l

	bchg.l	#0,d5
	bchg.b	#0,(a2)
	bchg.b	#0,(a2)+
	bchg.b	#0,-(a2)
	bchg.b	#0,$7FFF(a2)
	bchg.b	#0,$7F(a2,d5.w)
	bchg.b	#0,($FFFFFFFF).w
	bchg.b	#0,($FFFFFFFF).l

	bchg	#0,d5
	bchg	#0,(a2)
	bchg	#0,(a2)+
	bchg	#0,-(a2)
	bchg	#0,$7FFF(a2)
	bchg	#0,$7F(a2,d5.w)
	bchg	#0,($FFFFFFFF).w
	bchg	#0,($FFFFFFFF).l

	bclr.l	d2,d5
	bclr.b	d5,(a2)
	bclr.b	d5,(a2)+
	bclr.b	d5,-(a2)
	bclr.b	d5,$7FFF(a2)
	bclr.b	d5,$7F(a2,d5.w)
	bclr.b	d5,($FFFFFFFF).w
	bclr.b	d5,($FFFFFFFF).l

	bclr	d2,d5
	bclr	d5,(a2)
	bclr	d5,(a2)+
	bclr	d5,-(a2)
	bclr	d5,$7FFF(a2)
	bclr	d5,$7F(a2,d5.w)
	bclr	d5,($FFFFFFFF).w
	bclr	d5,($FFFFFFFF).l

	bclr.l	#0,d5
	bclr.b	#0,(a2)
	bclr.b	#0,(a2)+
	bclr.b	#0,-(a2)
	bclr.b	#0,$7FFF(a2)
	bclr.b	#0,$7F(a2,d5.w)
	bclr.b	#0,($FFFFFFFF).w
	bclr.b	#0,($FFFFFFFF).l

	bclr	#0,d5
	bclr	#0,(a2)
	bclr	#0,(a2)+
	bclr	#0,-(a2)
	bclr	#0,$7FFF(a2)
	bclr	#0,$7F(a2,d5.w)
	bclr	#0,($FFFFFFFF).w
	bclr	#0,($FFFFFFFF).l

	bset.l	d2,d5
	bset.b	d5,(a2)
	bset.b	d5,(a2)+
	bset.b	d5,-(a2)
	bset.b	d5,$7FFF(a2)
	bset.b	d5,$7F(a2,d5.w)
	bset.b	d5,($FFFFFFFF).w
	bset.b	d5,($FFFFFFFF).l

	bset	d2,d5
	bset	d5,(a2)
	bset	d5,(a2)+
	bset	d5,-(a2)
	bset	d5,$7FFF(a2)
	bset	d5,$7F(a2,d5.w)
	bset	d5,($FFFFFFFF).w
	bset	d5,($FFFFFFFF).l

	bset.l	#0,d5
	bset.b	#0,(a2)
	bset.b	#0,(a2)+
	bset.b	#0,-(a2)
	bset.b	#0,$7FFF(a2)
	bset.b	#0,$7F(a2,d5.w)
	bset.b	#0,($FFFFFFFF).w
	bset.b	#0,($FFFFFFFF).l

	bset	#0,d5
	bset	#0,(a2)
	bset	#0,(a2)+
	bset	#0,-(a2)
	bset	#0,$7FFF(a2)
	bset	#0,$7F(a2,d5.w)
	bset	#0,($FFFFFFFF).w
	bset	#0,($FFFFFFFF).l

	movep.w	$7FFF(a2),d5
	movep.w	d5,$7FFF(a2)
	movep.l	$7FFF(a2),d5
	movep.l	d5,$7FFF(a2)
		
	movea.w	d5,a2
	movea.w	a5,a2
	movea.w	(a2),a2
	movea.w	(a2)+,a2
	movea.w	-(a2),a2
	movea.w	$7FFF(a2),a2
	movea.w	$7F(a2,d5.w),a2
	movea.w	($FFFFFFFF).w,a2
	movea.w	($FFFFFFFF).l,a2
	movea.w	*(pc),a2
	movea.w	*(pc,d5.w),a2
	movea.l	d5,a2
	movea.l	a5,a2
	movea.l	(a2),a2
	movea.l	(a2)+,a2
	movea.l	-(a2),a2
	movea.l	$7FFF(a2),a2
	movea.l	$7F(a2,d5.w),a2
	movea.l	($FFFFFFFF).w,a2
	movea.l	($FFFFFFFF).l,a2
	movea.l	*(pc),a2
	movea.l	*(pc,d5.w),a2

	move.b	d2,d5
	move.b	d5,(a2)
	move.b	d5,(a2)+
	move.b	d5,-(a2)
	move.b	d5,$7FFF(a2)
	move.b	d5,$7F(a2,d5.w)
	move.b	d5,($FFFFFFFF).w
	move.b	d5,($FFFFFFFF).l
	move.b	(a2),d5
	move.b	(a2),(a2)
	move.b	(a2),(a2)+
	move.b	(a2),-(a2)
	move.b	(a2),$7FFF(a2)
	move.b	(a2),$7F(a2,d5.w)
	move.b	(a2),($FFFFFFFF).w
	move.b	(a2),($FFFFFFFF).l
	move.b	(a2)+,d5
	move.b	(a2)+,(a2)
	move.b	(a2)+,(a2)+
	move.b	(a2)+,-(a2)
	move.b	(a2)+,$7FFF(a2)
	move.b	(a2)+,$7F(a2,d5.w)
	move.b	(a2)+,($FFFFFFFF).w
	move.b	(a2)+,($FFFFFFFF).l
	move.b	-(a2),d5
	move.b	-(a2),(a2)
	move.b	-(a2),(a2)+
	move.b	-(a2),-(a2)
	move.b	-(a2),$7FFF(a2)
	move.b	-(a2),$7F(a2,d5.w)
	move.b	-(a2),($FFFFFFFF).w
	move.b	-(a2),($FFFFFFFF).l
	move.b	$7FFF(a2),d5
	move.b	$7FFF(a2),(a2)
	move.b	$7FFF(a2),(a2)+
	move.b	$7FFF(a2),-(a2)
	move.b	$7FFF(a2),$7FFF(a2)
	move.b	$7FFF(a2),$7F(a2,d5.w)
	move.b	$7FFF(a2),($FFFFFFFF).w
	move.b	$7FFF(a2),($FFFFFFFF).l
	move.b	$7F(a2,d5.w),d5
	move.b	$7F(a2,d5.w),(a2)
	move.b	$7F(a2,d5.w),(a2)+
	move.b	$7F(a2,d5.w),-(a2)
	move.b	$7F(a2,d5.w),$7FFF(a2)
	move.b	$7F(a2,d5.w),$7F(a2,d5.w)
	move.b	$7F(a2,d5.w),($FFFFFFFF).w
	move.b	$7F(a2,d5.w),($FFFFFFFF).l
	move.b	($FFFFFFFF).w,d5
	move.b	($FFFFFFFF).w,(a2)
	move.b	($FFFFFFFF).w,(a2)+
	move.b	($FFFFFFFF).w,-(a2)
	move.b	($FFFFFFFF).w,$7FFF(a2)
	move.b	($FFFFFFFF).w,$7F(a2,d5.w)
	move.b	($FFFFFFFF).w,($FFFFFFFF).w
	move.b	($FFFFFFFF).w,($FFFFFFFF).l
	move.b	($FFFFFFFF).l,d5
	move.b	($FFFFFFFF).l,(a2)
	move.b	($FFFFFFFF).l,(a2)+
	move.b	($FFFFFFFF).l,-(a2)
	move.b	($FFFFFFFF).l,$7FFF(a2)
	move.b	($FFFFFFFF).l,$7F(a2,d5.w)
	move.b	($FFFFFFFF).l,($FFFFFFFF).w
	move.b	($FFFFFFFF).l,($FFFFFFFF).l
	move.b	#$FF,d5
	move.b	#$FF,(a2)
	move.b	#$FF,(a2)+
	move.b	#$FF,-(a2)
	move.b	#$FF,$7FFF(a2)
	move.b	#$FF,$7F(a2,d5.w)
	move.b	#$FF,($FFFFFFFF).w
	move.b	#$FF,($FFFFFFFF).l
	move.b	*(pc),d5
	move.b	*(pc),(a2)
	move.b	*(pc),(a2)+
	move.b	*(pc),-(a2)
	move.b	*(pc),$7FFF(a2)
	move.b	*(pc),$7F(a2,d5.w)
	move.b	*(pc),($FFFFFFFF).w
	move.b	*(pc),($FFFFFFFF).l
	move.b	*(pc,d5.w),d5
	move.b	*(pc,d5.w),(a2)
	move.b	*(pc,d5.w),(a2)+
	move.b	*(pc,d5.w),-(a2)
	move.b	*(pc,d5.w),$7FFF(a2)
	move.b	*(pc,d5.w),$7F(a2,d5.w)
	move.b	*(pc,d5.w),($FFFFFFFF).w
	move.b	*(pc,d5.w),($FFFFFFFF).l
	move.w	d2,d5
	move.w	d5,(a2)
	move.w	d5,(a2)+
	move.w	d5,-(a2)
	move.w	d5,$7FFF(a2)
	move.w	d5,$7F(a2,d5.w)
	move.w	d5,($FFFFFFFF).w
	move.w	d5,($FFFFFFFF).l
	move.w	a2,d5
	move.w	a2,(a2)
	move.w	a2,(a2)+
	move.w	a2,-(a2)
	move.w	a2,$7FFF(a2)
	move.w	a2,$7F(a2,d5.w)
	move.w	a2,($FFFFFFFF).w
	move.w	a2,($FFFFFFFF).l
	move.w	(a2),d5
	move.w	(a2),(a2)
	move.w	(a2),(a2)+
	move.w	(a2),-(a2)
	move.w	(a2),$7FFF(a2)
	move.w	(a2),$7F(a2,d5.w)
	move.w	(a2),($FFFFFFFF).w
	move.w	(a2),($FFFFFFFF).l
	move.w	(a2)+,d5
	move.w	(a2)+,(a2)
	move.w	(a2)+,(a2)+
	move.w	(a2)+,-(a2)
	move.w	(a2)+,$7FFF(a2)
	move.w	(a2)+,$7F(a2,d5.w)
	move.w	(a2)+,($FFFFFFFF).w
	move.w	(a2)+,($FFFFFFFF).l
	move.w	-(a2),d5
	move.w	-(a2),(a2)
	move.w	-(a2),(a2)+
	move.w	-(a2),-(a2)
	move.w	-(a2),$7FFF(a2)
	move.w	-(a2),$7F(a2,d5.w)
	move.w	-(a2),($FFFFFFFF).w
	move.w	-(a2),($FFFFFFFF).l
	move.w	$7FFF(a2),d5
	move.w	$7FFF(a2),(a2)
	move.w	$7FFF(a2),(a2)+
	move.w	$7FFF(a2),-(a2)
	move.w	$7FFF(a2),$7FFF(a2)
	move.w	$7FFF(a2),$7F(a2,d5.w)
	move.w	$7FFF(a2),($FFFFFFFF).w
	move.w	$7FFF(a2),($FFFFFFFF).l
	move.w	$7F(a2,d5.w),d5
	move.w	$7F(a2,d5.w),(a2)
	move.w	$7F(a2,d5.w),(a2)+
	move.w	$7F(a2,d5.w),-(a2)
	move.w	$7F(a2,d5.w),$7FFF(a2)
	move.w	$7F(a2,d5.w),$7F(a2,d5.w)
	move.w	$7F(a2,d5.w),($FFFFFFFF).w
	move.w	$7F(a2,d5.w),($FFFFFFFF).l
	move.w	($FFFFFFFF).w,d5
	move.w	($FFFFFFFF).w,(a2)
	move.w	($FFFFFFFF).w,(a2)+
	move.w	($FFFFFFFF).w,-(a2)
	move.w	($FFFFFFFF).w,$7FFF(a2)
	move.w	($FFFFFFFF).w,$7F(a2,d5.w)
	move.w	($FFFFFFFF).w,($FFFFFFFF).w
	move.w	($FFFFFFFF).w,($FFFFFFFF).l
	move.w	($FFFFFFFF).l,d5
	move.w	($FFFFFFFF).l,(a2)
	move.w	($FFFFFFFF).l,(a2)+
	move.w	($FFFFFFFF).l,-(a2)
	move.w	($FFFFFFFF).l,$7FFF(a2)
	move.w	($FFFFFFFF).l,$7F(a2,d5.w)
	move.w	($FFFFFFFF).l,($FFFFFFFF).w
	move.w	($FFFFFFFF).l,($FFFFFFFF).l
	move.w	#$FFFF,d5
	move.w	#$FFFF,(a2)
	move.w	#$FFFF,(a2)+
	move.w	#$FFFF,-(a2)
	move.w	#$FFFF,$7FFF(a2)
	move.w	#$FFFF,$7F(a2,d5.w)
	move.w	#$FFFF,($FFFFFFFF).w
	move.w	#$FF,($FFFFFFFF).l
	move.w	*(pc),d5
	move.w	*(pc),(a2)
	move.w	*(pc),(a2)+
	move.w	*(pc),-(a2)
	move.w	*(pc),$7FFF(a2)
	move.w	*(pc),$7F(a2,d5.w)
	move.w	*(pc),($FFFFFFFF).w
	move.w	*(pc),($FFFFFFFF).l
	move.w	*(pc,d5.w),d5
	move.w	*(pc,d5.w),(a2)
	move.w	*(pc,d5.w),(a2)+
	move.w	*(pc,d5.w),-(a2)
	move.w	*(pc,d5.w),$7FFF(a2)
	move.w	*(pc,d5.w),$7F(a2,d5.w)
	move.w	*(pc,d5.w),($FFFFFFFF).w
	move.w	*(pc,d5.w),($FFFFFFFF).l
	move.l	d2,d5
	move.l	d5,(a2)
	move.l	d5,(a2)+
	move.l	d5,-(a2)
	move.l	d5,$7FFF(a2)
	move.l	d5,$7F(a2,d5.w)
	move.l	d5,($FFFFFFFF).w
	move.l	d5,($FFFFFFFF).l
	move.l	a2,d5
	move.l	a2,(a2)
	move.l	a2,(a2)+
	move.l	a2,-(a2)
	move.l	a2,$7FFF(a2)
	move.l	a2,$7F(a2,d5.w)
	move.l	a2,($FFFFFFFF).w
	move.l	a2,($FFFFFFFF).l
	move.l	(a2),d5
	move.l	(a2),(a2)
	move.l	(a2),(a2)+
	move.l	(a2),-(a2)
	move.l	(a2),$7FFF(a2)
	move.l	(a2),$7F(a2,d5.w)
	move.l	(a2),($FFFFFFFF).w
	move.l	(a2),($FFFFFFFF).l
	move.l	(a2)+,d5
	move.l	(a2)+,(a2)
	move.l	(a2)+,(a2)+
	move.l	(a2)+,-(a2)
	move.l	(a2)+,$7FFF(a2)
	move.l	(a2)+,$7F(a2,d5.w)
	move.l	(a2)+,($FFFFFFFF).w
	move.l	(a2)+,($FFFFFFFF).l
	move.l	-(a2),d5
	move.l	-(a2),(a2)
	move.l	-(a2),(a2)+
	move.l	-(a2),-(a2)
	move.l	-(a2),$7FFF(a2)
	move.l	-(a2),$7F(a2,d5.w)
	move.l	-(a2),($FFFFFFFF).w
	move.l	-(a2),($FFFFFFFF).l
	move.l	$7FFF(a2),d5
	move.l	$7FFF(a2),(a2)
	move.l	$7FFF(a2),(a2)+
	move.l	$7FFF(a2),-(a2)
	move.l	$7FFF(a2),$7FFF(a2)
	move.l	$7FFF(a2),$7F(a2,d5.w)
	move.l	$7FFF(a2),($FFFFFFFF).w
	move.l	$7FFF(a2),($FFFFFFFF).l
	move.l	$7F(a2,d5.w),d5
	move.l	$7F(a2,d5.w),(a2)
	move.l	$7F(a2,d5.w),(a2)+
	move.l	$7F(a2,d5.w),-(a2)
	move.l	$7F(a2,d5.w),$7FFF(a2)
	move.l	$7F(a2,d5.w),$7F(a2,d5.w)
	move.l	$7F(a2,d5.w),($FFFFFFFF).w
	move.l	$7F(a2,d5.w),($FFFFFFFF).l
	move.l	($FFFFFFFF).w,d5
	move.l	($FFFFFFFF).w,(a2)
	move.l	($FFFFFFFF).w,(a2)+
	move.l	($FFFFFFFF).w,-(a2)
	move.l	($FFFFFFFF).w,$7FFF(a2)
	move.l	($FFFFFFFF).w,$7F(a2,d5.w)
	move.l	($FFFFFFFF).w,($FFFFFFFF).w
	move.l	($FFFFFFFF).w,($FFFFFFFF).l
	move.l	($FFFFFFFF).l,d5
	move.l	($FFFFFFFF).l,(a2)
	move.l	($FFFFFFFF).l,(a2)+
	move.l	($FFFFFFFF).l,-(a2)
	move.l	($FFFFFFFF).l,$7FFF(a2)
	move.l	($FFFFFFFF).l,$7F(a2,d5.w)
	move.l	($FFFFFFFF).l,($FFFFFFFF).w
	move.l	($FFFFFFFF).l,($FFFFFFFF).l
	move.l	#$FFFFFFFF,d5
	move.l	#$FFFFFFFF,(a2)
	move.l	#$FFFFFFFF,(a2)+
	move.l	#$FFFFFFFF,-(a2)
	move.l	#$FFFFFFFF,$7FFF(a2)
	move.l	#$FFFFFFFF,$7F(a2,d5.w)
	move.l	#$FFFFFFFF,($FFFFFFFF).w
	move.l	#$FFFFFFFF,($FFFFFFFF).l
	move.l	*(pc),d5
	move.l	*(pc),(a2)
	move.l	*(pc),(a2)+
	move.l	*(pc),-(a2)
	move.l	*(pc),$7FFF(a2)
	move.l	*(pc),$7F(a2,d5.w)
	move.l	*(pc),($FFFFFFFF).w
	move.l	*(pc),($FFFFFFFF).l
	move.l	*(pc,d5.w),d5
	move.l	*(pc,d5.w),(a2)
	move.l	*(pc,d5.w),(a2)+
	move.l	*(pc,d5.w),-(a2)
	move.l	*(pc,d5.w),$7FFF(a2)
	move.l	*(pc,d5.w),$7F(a2,d5.w)
	move.l	*(pc,d5.w),($FFFFFFFF).w
	move.l	*(pc,d5.w),($FFFFFFFF).l
	move.w	sr,d5
	move.w	sr,(a2)
	move.w	sr,(a2)+
	move.w	sr,-(a2)
	move.w	sr,$7FFF(a2)
	move.w	sr,$7F(a2,d5.w)
	move.w	sr,($FFFFFFFF).w
	move.w	sr,($FFFFFFFF).l
	move.w	d5,ccr
	move.w	(a2),ccr
	move.w	(a2)+,ccr
	move.w	-(a2),ccr
	move.w	$7FFF(a2),ccr
	move.w	$7F(a2,d5.w),ccr
	move.w	($FFFFFFFF).w,ccr
	move.w	($FFFFFFFF).l,ccr
	move.w	#$FFFF,ccr
	move.w	*(pc),ccr
	move.w	*(pc,d5.w),ccr
	move.w	d5,sr
	move.w	(a2),sr
	move.w	(a2)+,sr
	move.w	-(a2),sr
	move.w	$7FFF(a2),sr
	move.w	$7F(a2,d5.w),sr
	move.w	($FFFFFFFF).w,sr
	move.w	($FFFFFFFF).l,sr
	move.w	#$FFFF,sr
	move.w	*(pc),sr
	move.w	*(pc,d5.w),sr

	negx.b	d5
	negx.b	(a2)
	negx.b	(a2)+
	negx.b	-(a2)
	negx.b	$7FFF(a2)
	negx.b	$7F(a2,d5.w)
	negx.b	($FFFFFFFF).w
	negx.b	($FFFFFFFF).l
	negx.w	d5
	negx.w	(a2)
	negx.w	(a2)+
	negx.w	-(a2)
	negx.w	$7FFF(a2)
	negx.w	$7F(a2,d5.w)
	negx.w	($FFFFFFFF).w
	negx.w	($FFFFFFFF).l
	negx.l	d5
	negx.l	(a2)
	negx.l	(a2)+
	negx.l	-(a2)
	negx.l	$7FFF(a2)
	negx.l	$7F(a2,d5.w)
	negx.l	($FFFFFFFF).w
	negx.l	($FFFFFFFF).l

	clr.b	d5
	clr.b	(a2)
	clr.b	(a2)+
	clr.b	-(a2)
	clr.b	$7FFF(a2)
	clr.b	$7F(a2,d5.w)
	clr.b	($FFFFFFFF).w
	clr.b	($FFFFFFFF).l
	clr.w	d5
	clr.w	(a2)
	clr.w	(a2)+
	clr.w	-(a2)
	clr.w	$7FFF(a2)
	clr.w	$7F(a2,d5.w)
	clr.w	($FFFFFFFF).w
	clr.w	($FFFFFFFF).l
	clr.l	d5
	clr.l	(a2)
	clr.l	(a2)+
	clr.l	-(a2)
	clr.l	$7FFF(a2)
	clr.l	$7F(a2,d5.w)
	clr.l	($FFFFFFFF).w
	clr.l	($FFFFFFFF).l

	neg.b	d5
	neg.b	(a2)
	neg.b	(a2)+
	neg.b	-(a2)
	neg.b	$7FFF(a2)
	neg.b	$7F(a2,d5.w)
	neg.b	($FFFFFFFF).w
	neg.b	($FFFFFFFF).l
	neg.w	d5
	neg.w	(a2)
	neg.w	(a2)+
	neg.w	-(a2)
	neg.w	$7FFF(a2)
	neg.w	$7F(a2,d5.w)
	neg.w	($FFFFFFFF).w
	neg.w	($FFFFFFFF).l
	neg.l	d5
	neg.l	(a2)
	neg.l	(a2)+
	neg.l	-(a2)
	neg.l	$7FFF(a2)
	neg.l	$7F(a2,d5.w)
	neg.l	($FFFFFFFF).w
	neg.l	($FFFFFFFF).l

	not.b	d5
	not.b	(a2)
	not.b	(a2)+
	not.b	-(a2)
	not.b	$7FFF(a2)
	not.b	$7F(a2,d5.w)
	not.b	($FFFFFFFF).w
	not.b	($FFFFFFFF).l
	not.w	d5
	not.w	(a2)
	not.w	(a2)+
	not.w	-(a2)
	not.w	$7FFF(a2)
	not.w	$7F(a2,d5.w)
	not.w	($FFFFFFFF).w
	not.w	($FFFFFFFF).l
	not.l	d5
	not.l	(a2)
	not.l	(a2)+
	not.l	-(a2)
	not.l	$7FFF(a2)
	not.l	$7F(a2,d5.w)
	not.l	($FFFFFFFF).w
	not.l	($FFFFFFFF).l

	ext.w	d5
	ext.l	d5

	nbcd.b	d5
	nbcd.b	(a2)
	nbcd.b	(a2)+
	nbcd.b	-(a2)
	nbcd.b	$7FFF(a2)
	nbcd.b	$7F(a2,d5.w)
	nbcd.b	($FFFFFFFF).w
	nbcd.b	($FFFFFFFF).l
	nbcd	d5
	nbcd	(a2)
	nbcd	(a2)+
	nbcd	-(a2)
	nbcd	$7FFF(a2)
	nbcd	$7F(a2,d5.w)
	nbcd	($FFFFFFFF).w
	nbcd	($FFFFFFFF).l

	swap.w	d5
	swap	d5

	pea.l	(a2)
	pea.l	$7FFF(a2)
	pea.l	$7F(a2,d5.w)
	pea.l	($FFFFFFFF).w
	pea.l	($FFFFFFFF).l
	pea.l	*(pc)
	pea.l	*(pc,d5.w)
	pea	(a2)
	pea	$7FFF(a2)
	pea	$7F(a2,d5.w)
	pea	($FFFFFFFF).w
	pea	($FFFFFFFF).l
	pea	*(pc)
	pea	*(pc,d5.w)

	illegal

	tas.b	d5
	tas.b	(a2)
	tas.b	(a2)+
	tas.b	-(a2)
	tas.b	$7FFF(a2)
	tas.b	$7F(a2,d5.w)
	tas.b	($FFFFFFFF).w
	tas.b	($FFFFFFFF).l
	tas	d5
	tas	(a2)
	tas	(a2)+
	tas	-(a2)
	tas	$7FFF(a2)
	tas	$7F(a2,d5.w)
	tas	($FFFFFFFF).w
	tas	($FFFFFFFF).l

	tst.b	d5
	tst.b	(a2)
	tst.b	(a2)+
	tst.b	-(a2)
	tst.b	$7FFF(a2)
	tst.b	$7F(a2,d5.w)
	tst.b	($FFFFFFFF).w
	tst.b	($FFFFFFFF).l
	tst.w	d5
	tst.w	(a2)
	tst.w	(a2)+
	tst.w	-(a2)
	tst.w	$7FFF(a2)
	tst.w	$7F(a2,d5.w)
	tst.w	($FFFFFFFF).w
	tst.w	($FFFFFFFF).l
	tst.l	d5
	tst.l	(a2)
	tst.l	(a2)+
	tst.l	-(a2)
	tst.l	$7FFF(a2)
	tst.l	$7F(a2,d5.w)
	tst.l	($FFFFFFFF).w
	tst.l	($FFFFFFFF).l

	trap	#2

	link.w	a2,#4
	link	a2,#4

	unlk	a2

	move.l	usp,a2
	move.l	a2,usp
	move	usp,a2
	move	a2,usp

	reset

	nop

	stop	#$2700

	rte

	rts

	trapv

	rtr

	jsr	(a2)
	jsr	$7FFF(a2)
	jsr	$7F(a2,d5.w)
	jsr	($FFFFFFFF).w
	jsr	($FFFFFFFF).l
	jsr	*(pc)
	jsr	*(pc,d5.w)

	jmp	(a2)
	jmp	$7FFF(a2)
	jmp	$7F(a2,d5.w)
	jmp	($FFFFFFFF).w
	jmp	($FFFFFFFF).l
	jmp	*(pc)
	jmp	*(pc,d5.w)

	movem.w	d5-a7,(a2)
	movem.w	d5-a7,-(a2)
	movem.w	d5-a7,$7FFF(a2)
	movem.w	d5-a7,$7F(a2,d5.w)
	movem.w	d5-a7,($FFFFFFFF).w
	movem.w	d5-a7,($FFFFFFFF).l
	movem.w	(a2),d5-a7
	movem.w	(a2)+,d5-a7
	movem.w	$7FFF(a2),d5-a7
	movem.w	$7F(a2,d5.w),d5-a7
	movem.w	($FFFFFFFF).w,d5-a7
	movem.w	($FFFFFFFF).l,d5-a7
	movem.w	*(pc),d5-a7
	movem.w	*(pc,d5.w),d5-a7
	movem.l	d5-a7,(a2)
	movem.l	d5-a7,-(a2)
	movem.l	d5-a7,$7FFF(a2)
	movem.l	d5-a7,$7F(a2,d5.w)
	movem.l	d5-a7,($FFFFFFFF).w
	movem.l	d5-a7,($FFFFFFFF).l
	movem.l	(a2),d5-a7
	movem.l	(a2)+,d5-a7
	movem.l	$7FFF(a2),d5-a7
	movem.l	$7F(a2,d5.w),d5-a7
	movem.l	($FFFFFFFF).w,d5-a7
	movem.l	($FFFFFFFF).l,d5-a7
	movem.l	*(pc),d5-a7
	movem.l	*(pc,d5.w),d5-a7

	lea.l	(a2),a2
	lea.l	$7FFF(a2),a2
	lea.l	$7F(a2,d5.w),a2
	lea.l	($FFFFFFFF).w,a2
	lea.l	($FFFFFFFF).l,a2
	lea.l	*(pc),a2
	lea.l	*(pc,d5.w),a2
	lea	(a2),a2
	lea	$7FFF(a2),a2
	lea	$7F(a2,d5.w),a2
	lea	($FFFFFFFF).w,a2
	lea	($FFFFFFFF).l,a2
	lea	*(pc),a2
	lea	*(pc,d5.w),a2

	chk.w	d2,d5
	chk.w	(a2),d5
	chk.w	(a2)+,d5
	chk.w	-(a2),d5
	chk.w	$7FFF(a2),d5
	chk.w	$7F(a2,d5.w),d5
	chk.w	($FFFFFFFF).w,d5
	chk.w	($FFFFFFFF).l,d5
	chk.w	#$FFFF,d5
	chk.w	*(pc),d5
	chk.w	*(pc,d5.w),d5
	chk	d2,d5
	chk	(a2),d5
	chk	(a2)+,d5
	chk	-(a2),d5
	chk	$7FFF(a2),d5
	chk	$7F(a2,d5.w),d5
	chk	($FFFFFFFF).w,d5
	chk	($FFFFFFFF).l,d5
	chk	#$FFFF,d5
	chk	*(pc),d5
	chk	*(pc,d5.w),d5

	addq.b	#1,d5
	addq.b	#1,(a2)
	addq.b	#1,(a2)+
	addq.b	#1,-(a2)
	addq.b	#1,$7FFF(a2)
	addq.b	#1,$7F(a2,d5.w)
	addq.b	#1,($FFFFFFFF).w
	addq.b	#1,($FFFFFFFF).l
	addq.w	#1,d5
	addq.w	#1,a2
	addq.w	#1,(a2)
	addq.w	#1,(a2)+
	addq.w	#1,-(a2)
	addq.w	#1,$7FFF(a2)
	addq.w	#1,$7F(a2,d5.w)
	addq.w	#1,($FFFFFFFF).w
	addq.w	#1,($FFFFFFFF).l
	addq.l	#1,d5
	addq.l	#1,a2
	addq.l	#1,(a2)
	addq.l	#1,(a2)+
	addq.l	#1,-(a2)
	addq.l	#1,$7FFF(a2)
	addq.l	#1,$7F(a2,d5.w)
	addq.l	#1,($FFFFFFFF).w
	addq.l	#1,($FFFFFFFF).l

	subq.b	#1,d5
	subq.b	#1,(a2)
	subq.b	#1,(a2)+
	subq.b	#1,-(a2)
	subq.b	#1,$7FFF(a2)
	subq.b	#1,$7F(a2,d5.w)
	subq.b	#1,($FFFFFFFF).w
	subq.b	#1,($FFFFFFFF).l
	subq.w	#1,d5
	subq.w	#1,a2
	subq.w	#1,(a2)
	subq.w	#1,(a2)+
	subq.w	#1,-(a2)
	subq.w	#1,$7FFF(a2)
	subq.w	#1,$7F(a2,d5.w)
	subq.w	#1,($FFFFFFFF).w
	subq.w	#1,($FFFFFFFF).l
	subq.l	#1,d5
	subq.l	#1,a2
	subq.l	#1,(a2)
	subq.l	#1,(a2)+
	subq.l	#1,-(a2)
	subq.l	#1,$7FFF(a2)
	subq.l	#1,$7F(a2,d5.w)
	subq.l	#1,($FFFFFFFF).w
	subq.l	#1,($FFFFFFFF).l

	st.b	d5
	st.b	(a2)
	st.b	(a2)+
	st.b	-(a2)
	st.b	$7FFF(a2)
	st.b	$7F(a2,d5.w)
	st.b	($FFFFFFFF).w
	st.b	($FFFFFFFF).l
	st	d5
	st	(a2)
	st	(a2)+
	st	-(a2)
	st	$7FFF(a2)
	st	$7F(a2,d5.w)
	st	($FFFFFFFF).w
	st	($FFFFFFFF).l

	sf.b	d5
	sf.b	(a2)
	sf.b	(a2)+
	sf.b	-(a2)
	sf.b	$7FFF(a2)
	sf.b	$7F(a2,d5.w)
	sf.b	($FFFFFFFF).w
	sf.b	($FFFFFFFF).l
	sf	d5
	sf	(a2)
	sf	(a2)+
	sf	-(a2)
	sf	$7FFF(a2)
	sf	$7F(a2,d5.w)
	sf	($FFFFFFFF).w
	sf	($FFFFFFFF).l

	shi.b	d5
	shi.b	(a2)
	shi.b	(a2)+
	shi.b	-(a2)
	shi.b	$7FFF(a2)
	shi.b	$7F(a2,d5.w)
	shi.b	($FFFFFFFF).w
	shi.b	($FFFFFFFF).l
	shi	d5
	shi	(a2)
	shi	(a2)+
	shi	-(a2)
	shi	$7FFF(a2)
	shi	$7F(a2,d5.w)
	shi	($FFFFFFFF).w
	shi	($FFFFFFFF).l

	sls.b	d5
	sls.b	(a2)
	sls.b	(a2)+
	sls.b	-(a2)
	sls.b	$7FFF(a2)
	sls.b	$7F(a2,d5.w)
	sls.b	($FFFFFFFF).w
	sls.b	($FFFFFFFF).l
	sls	d5
	sls	(a2)
	sls	(a2)+
	sls	-(a2)
	sls	$7FFF(a2)
	sls	$7F(a2,d5.w)
	sls	($FFFFFFFF).w
	sls	($FFFFFFFF).l

	scc.b	d5
	scc.b	(a2)
	scc.b	(a2)+
	scc.b	-(a2)
	scc.b	$7FFF(a2)
	scc.b	$7F(a2,d5.w)
	scc.b	($FFFFFFFF).w
	scc.b	($FFFFFFFF).l
	scc	d5
	scc	(a2)
	scc	(a2)+
	scc	-(a2)
	scc	$7FFF(a2)
	scc	$7F(a2,d5.w)
	scc	($FFFFFFFF).w
	scc	($FFFFFFFF).l

	scs.b	d5
	scs.b	(a2)
	scs.b	(a2)+
	scs.b	-(a2)
	scs.b	$7FFF(a2)
	scs.b	$7F(a2,d5.w)
	scs.b	($FFFFFFFF).w
	scs.b	($FFFFFFFF).l
	scs	d5
	scs	(a2)
	scs	(a2)+
	scs	-(a2)
	scs	$7FFF(a2)
	scs	$7F(a2,d5.w)
	scs	($FFFFFFFF).w
	scs	($FFFFFFFF).l

	sne.b	d5
	sne.b	(a2)
	sne.b	(a2)+
	sne.b	-(a2)
	sne.b	$7FFF(a2)
	sne.b	$7F(a2,d5.w)
	sne.b	($FFFFFFFF).w
	sne.b	($FFFFFFFF).l
	sne	d5
	sne	(a2)
	sne	(a2)+
	sne	-(a2)
	sne	$7FFF(a2)
	sne	$7F(a2,d5.w)
	sne	($FFFFFFFF).w
	sne	($FFFFFFFF).l

	seq.b	d5
	seq.b	(a2)
	seq.b	(a2)+
	seq.b	-(a2)
	seq.b	$7FFF(a2)
	seq.b	$7F(a2,d5.w)
	seq.b	($FFFFFFFF).w
	seq.b	($FFFFFFFF).l
	seq	d5
	seq	(a2)
	seq	(a2)+
	seq	-(a2)
	seq	$7FFF(a2)
	seq	$7F(a2,d5.w)
	seq	($FFFFFFFF).w
	seq	($FFFFFFFF).l

	svc.b	d5
	svc.b	(a2)
	svc.b	(a2)+
	svc.b	-(a2)
	svc.b	$7FFF(a2)
	svc.b	$7F(a2,d5.w)
	svc.b	($FFFFFFFF).w
	svc.b	($FFFFFFFF).l
	svc	d5
	svc	(a2)
	svc	(a2)+
	svc	-(a2)
	svc	$7FFF(a2)
	svc	$7F(a2,d5.w)
	svc	($FFFFFFFF).w
	svc	($FFFFFFFF).l

	svs.b	d5
	svs.b	(a2)
	svs.b	(a2)+
	svs.b	-(a2)
	svs.b	$7FFF(a2)
	svs.b	$7F(a2,d5.w)
	svs.b	($FFFFFFFF).w
	svs.b	($FFFFFFFF).l
	svs	d5
	svs	(a2)
	svs	(a2)+
	svs	-(a2)
	svs	$7FFF(a2)
	svs	$7F(a2,d5.w)
	svs	($FFFFFFFF).w
	svs	($FFFFFFFF).l

	spl.b	d5
	spl.b	(a2)
	spl.b	(a2)+
	spl.b	-(a2)
	spl.b	$7FFF(a2)
	spl.b	$7F(a2,d5.w)
	spl.b	($FFFFFFFF).w
	spl.b	($FFFFFFFF).l
	spl	d5
	spl	(a2)
	spl	(a2)+
	spl	-(a2)
	spl	$7FFF(a2)
	spl	$7F(a2,d5.w)
	spl	($FFFFFFFF).w
	spl	($FFFFFFFF).l

	smi.b	d5
	smi.b	(a2)
	smi.b	(a2)+
	smi.b	-(a2)
	smi.b	$7FFF(a2)
	smi.b	$7F(a2,d5.w)
	smi.b	($FFFFFFFF).w
	smi.b	($FFFFFFFF).l
	smi	d5
	smi	(a2)
	smi	(a2)+
	smi	-(a2)
	smi	$7FFF(a2)
	smi	$7F(a2,d5.w)
	smi	($FFFFFFFF).w
	smi	($FFFFFFFF).l

	sge.b	d5
	sge.b	(a2)
	sge.b	(a2)+
	sge.b	-(a2)
	sge.b	$7FFF(a2)
	sge.b	$7F(a2,d5.w)
	sge.b	($FFFFFFFF).w
	sge.b	($FFFFFFFF).l
	sge	d5
	sge	(a2)
	sge	(a2)+
	sge	-(a2)
	sge	$7FFF(a2)
	sge	$7F(a2,d5.w)
	sge	($FFFFFFFF).w
	sge	($FFFFFFFF).l

	slt.b	d5
	slt.b	(a2)
	slt.b	(a2)+
	slt.b	-(a2)
	slt.b	$7FFF(a2)
	slt.b	$7F(a2,d5.w)
	slt.b	($FFFFFFFF).w
	slt.b	($FFFFFFFF).l
	slt	d5
	slt	(a2)
	slt	(a2)+
	slt	-(a2)
	slt	$7FFF(a2)
	slt	$7F(a2,d5.w)
	slt	($FFFFFFFF).w
	slt	($FFFFFFFF).l

	sgt.b	d5
	sgt.b	(a2)
	sgt.b	(a2)+
	sgt.b	-(a2)
	sgt.b	$7FFF(a2)
	sgt.b	$7F(a2,d5.w)
	sgt.b	($FFFFFFFF).w
	sgt.b	($FFFFFFFF).l
	sgt	d5
	sgt	(a2)
	sgt	(a2)+
	sgt	-(a2)
	sgt	$7FFF(a2)
	sgt	$7F(a2,d5.w)
	sgt	($FFFFFFFF).w
	sgt	($FFFFFFFF).l

	sle.b	d5
	sle.b	(a2)
	sle.b	(a2)+
	sle.b	-(a2)
	sle.b	$7FFF(a2)
	sle.b	$7F(a2,d5.w)
	sle.b	($FFFFFFFF).w
	sle.b	($FFFFFFFF).l
	sle	d5
	sle	(a2)
	sle	(a2)+
	sle	-(a2)
	sle	$7FFF(a2)
	sle	$7F(a2,d5.w)
	sle	($FFFFFFFF).w
	sle	($FFFFFFFF).l

	shs.b	d5
	shs.b	(a2)
	shs.b	(a2)+
	shs.b	-(a2)
	shs.b	$7FFF(a2)
	shs.b	$7F(a2,d5.w)
	shs.b	($FFFFFFFF).w
	shs.b	($FFFFFFFF).l
	shs	d5
	shs	(a2)
	shs	(a2)+
	shs	-(a2)
	shs	$7FFF(a2)
	shs	$7F(a2,d5.w)
	shs	($FFFFFFFF).w
	shs	($FFFFFFFF).l

	slo.b	d5
	slo.b	(a2)
	slo.b	(a2)+
	slo.b	-(a2)
	slo.b	$7FFF(a2)
	slo.b	$7F(a2,d5.w)
	slo.b	($FFFFFFFF).w
	slo.b	($FFFFFFFF).l
	slo	d5
	slo	(a2)
	slo	(a2)+
	slo	-(a2)
	slo	$7FFF(a2)
	slo	$7F(a2,d5.w)
	slo	($FFFFFFFF).w
	slo	($FFFFFFFF).l

	dbt.w	d5,*
	dbf.w	d5,*
	dbhi.w	d5,*
	dbls.w	d5,*
	dbcc.w	d5,*
	dbcs.w	d5,*
	dbne.w	d5,*
	dbeq.w	d5,*
	dbvc.w	d5,*
	dbvs.w	d5,*
	dbpl.w	d5,*
	dbmi.w	d5,*
	dbge.w	d5,*
	dblt.w	d5,*
	dbgt.w	d5,*
	dble.w	d5,*
	dbhs.w	d5,*
	dblo.w	d5,*
	dbt	d5,*
	dbf	d5,*
	dbhi	d5,*
	dbls	d5,*
	dbcc	d5,*
	dbcs	d5,*
	dbne	d5,*
	dbeq	d5,*
	dbvc	d5,*
	dbvs	d5,*
	dbpl	d5,*
	dbmi	d5,*
	dbge	d5,*
	dblt	d5,*
	dbgt	d5,*
	dble	d5,*
	dbhs	d5,*
	dblo	d5,*

	bra.s	*
	bra.w	*

	bsr.s	*
	bsr.w	*

	bhi.s	*
	bls.s	*
	bcc.s	*
	bcs.s	*
	bne.s	*
	beq.s	*
	bvc.s	*
	bvs.s	*
	bpl.s	*
	bmi.s	*
	bge.s	*
	blt.s	*
	bgt.s	*
	ble.s	*
	bhs.s	*
	blo.s	*
	bhi.w	*
	bls.w	*
	bcc.w	*
	bcs.w	*
	bne.w	*
	beq.w	*
	bvc.w	*
	bvs.w	*
	bpl.w	*
	bmi.w	*
	bge.w	*
	blt.w	*
	bgt.w	*
	ble.w	*
	bhs.w	*
	blo.w	*

	moveq.l	#0,d5
	moveq	#0,d5

	divu.w	d2,d5
	divu.w	(a2),d5
	divu.w	(a2)+,d5
	divu.w	-(a2),d5
	divu.w	$7FFF(a2),d5
	divu.w	$7F(a2,d5.w),d5
	divu.w	($FFFFFFFF).w,d5
	divu.w	($FFFFFFFF).l,d5
	divu.w	#$FFFF,d5
	divu.w	*(pc),d5
	divu.w	*(pc,d5.w),d5
	divu	d2,d5
	divu	(a2),d5
	divu	(a2)+,d5
	divu	-(a2),d5
	divu	$7FFF(a2),d5
	divu	$7F(a2,d5.w),d5
	divu	($FFFFFFFF).w,d5
	divu	($FFFFFFFF).l,d5
	divu	#$FFFF,d5
	divu	*(pc),d5
	divu	*(pc,d5.w),d5

	divs.w	d2,d5
	divs.w	(a2),d5
	divs.w	(a2)+,d5
	divs.w	-(a2),d5
	divs.w	$7FFF(a2),d5
	divs.w	$7F(a2,d5.w),d5
	divs.w	($FFFFFFFF).w,d5
	divs.w	($FFFFFFFF).l,d5
	divs.w	#$FFFF,d5
	divs.w	*(pc),d5
	divs.w	*(pc,d5.w),d5
	divs	d2,d5
	divs	(a2),d5
	divs	(a2)+,d5
	divs	-(a2),d5
	divs	$7FFF(a2),d5
	divs	$7F(a2,d5.w),d5
	divs	($FFFFFFFF).w,d5
	divs	($FFFFFFFF).l,d5
	divs	#$FFFF,d5
	divs	*(pc),d5
	divs	*(pc,d5.w),d5

	sbcd.b	d2,d5
	sbcd.b	-(a2),-(a2)
	sbcd	d2,d5
	sbcd	-(a2),-(a2)

	or.b	d2,d5
	or.b	(a2),d5
	or.b	(a2)+,d5
	or.b	-(a2),d5
	or.b	$7FFF(a2),d5
	or.b	$7F(a2,d5.w),d5
	or.b	($FFFFFFFF).w,d5
	or.b	($FFFFFFFF).l,d5
	or.b	*(pc),d5
	or.b	*(pc,d5.w),d5
	or.b	d5,(a2)
	or.b	d5,(a2)+
	or.b	d5,-(a2)
	or.b	d5,$7FFF(a2)
	or.b	d5,$7F(a2,d5.w)
	or.b	d5,($FFFFFFFF).w
	or.b	d5,($FFFFFFFF).l
	or.w	d2,d5
	or.w	(a2),d5
	or.w	(a2)+,d5
	or.w	-(a2),d5
	or.w	$7FFF(a2),d5
	or.w	$7F(a2,d5.w),d5
	or.w	($FFFFFFFF).w,d5
	or.w	($FFFFFFFF).l,d5
	or.w	*(pc),d5
	or.w	*(pc,d5.w),d5
	or.w	d5,(a2)
	or.w	d5,(a2)+
	or.w	d5,-(a2)
	or.w	d5,$7FFF(a2)
	or.w	d5,$7F(a2,d5.w)
	or.w	d5,($FFFFFFFF).w
	or.w	d5,($FFFFFFFF).l
	or.l	d2,d5
	or.l	(a2),d5
	or.l	(a2)+,d5
	or.l	-(a2),d5
	or.l	$7FFF(a2),d5
	or.l	$7F(a2,d5.w),d5
	or.l	($FFFFFFFF).w,d5
	or.l	($FFFFFFFF).l,d5
	or.l	*(pc),d5
	or.l	*(pc,d5.w),d5
	or.l	d5,(a2)
	or.l	d5,(a2)+
	or.l	d5,-(a2)
	or.l	d5,$7FFF(a2)
	or.l	d5,$7F(a2,d5.w)
	or.l	d5,($FFFFFFFF).w
	or.l	d5,($FFFFFFFF).l

	sub.b	d2,d5
	sub.b	(a2),d5
	sub.b	(a2)+,d5
	sub.b	-(a2),d5
	sub.b	$7FFF(a2),d5
	sub.b	$7F(a2,d5.w),d5
	sub.b	($FFFFFFFF).w,d5
	sub.b	($FFFFFFFF).l,d5
	sub.b	*(pc),d5
	sub.b	*(pc,d5.w),d5
	sub.b	d5,(a2)
	sub.b	d5,(a2)+
	sub.b	d5,-(a2)
	sub.b	d5,$7FFF(a2)
	sub.b	d5,$7F(a2,d5.w)
	sub.b	d5,($FFFFFFFF).w
	sub.b	d5,($FFFFFFFF).l
	sub.w	d2,d5
	sub.w	(a2),d5
	sub.w	(a2)+,d5
	sub.w	-(a2),d5
	sub.w	$7FFF(a2),d5
	sub.w	$7F(a2,d5.w),d5
	sub.w	($FFFFFFFF).w,d5
	sub.w	($FFFFFFFF).l,d5
	sub.w	*(pc),d5
	sub.w	*(pc,d5.w),d5
	sub.w	d5,(a2)
	sub.w	d5,(a2)+
	sub.w	d5,-(a2)
	sub.w	d5,$7FFF(a2)
	sub.w	d5,$7F(a2,d5.w)
	sub.w	d5,($FFFFFFFF).w
	sub.w	d5,($FFFFFFFF).l
	sub.l	d2,d5
	sub.l	(a2),d5
	sub.l	(a2)+,d5
	sub.l	-(a2),d5
	sub.l	$7FFF(a2),d5
	sub.l	$7F(a2,d5.w),d5
	sub.l	($FFFFFFFF).w,d5
	sub.l	($FFFFFFFF).l,d5
	sub.l	*(pc),d5
	sub.l	*(pc,d5.w),d5
	sub.l	d5,(a2)
	sub.l	d5,(a2)+
	sub.l	d5,-(a2)
	sub.l	d5,$7FFF(a2)
	sub.l	d5,$7F(a2,d5.w)
	sub.l	d5,($FFFFFFFF).w
	sub.l	d5,($FFFFFFFF).l

	subx.b	d2,d5
	subx.b	-(a2),-(a2)
	subx.w	d2,d5
	subx.w	-(a2),-(a2)
	subx.l	d2,d5
	subx.l	-(a2),-(a2)

	suba.w	d5,a2
	suba.w	a5,a2
	suba.w	(a2),a2
	suba.w	(a2)+,a2
	suba.w	-(a2),a2
	suba.w	$7FFF(a2),a2
	suba.w	$7F(a2,d5.w),a2
	suba.w	($FFFFFFFF).w,a2
	suba.w	($FFFFFFFF).l,a2
	suba.w	#$7FFF,a2
	suba.w	*(pc),a2
	suba.w	*(pc,d5.w),a2
	suba.l	d5,a2
	suba.l	a5,a2
	suba.l	(a2),a2
	suba.l	(a2)+,a2
	suba.l	-(a2),a2
	suba.l	$7FFF(a2),a2
	suba.l	$7F(a2,d5.w),a2
	suba.l	($FFFFFFFF).w,a2
	suba.l	($FFFFFFFF).l,a2
	suba.l	#$7FFF,a2
	suba.l	*(pc),a2
	suba.l	*(pc,d5.w),a2

	eor.b	d2,d5
	eor.b	d5,(a2)
	eor.b	d5,(a2)+
	eor.b	d5,-(a2)
	eor.b	d5,$7FFF(a2)
	eor.b	d5,$7F(a2,d5.w)
	eor.b	d5,($FFFFFFFF).w
	eor.b	d5,($FFFFFFFF).l
	eor.w	d2,d5
	eor.w	d5,(a2)
	eor.w	d5,(a2)+
	eor.w	d5,-(a2)
	eor.w	d5,$7FFF(a2)
	eor.w	d5,$7F(a2,d5.w)
	eor.w	d5,($FFFFFFFF).w
	eor.w	d5,($FFFFFFFF).l
	eor.l	d2,d5
	eor.l	d5,(a2)
	eor.l	d5,(a2)+
	eor.l	d5,-(a2)
	eor.l	d5,$7FFF(a2)
	eor.l	d5,$7F(a2,d5.w)
	eor.l	d5,($FFFFFFFF).w
	eor.l	d5,($FFFFFFFF).l

	cmpm.b	(a2)+,(a1)+
	cmpm.w	(a2)+,(a1)+
	cmpm.l	(a2)+,(a1)+

	cmp.b	d2,d5
	cmp.b	(a2),d5
	cmp.b	(a2)+,d5
	cmp.b	-(a2),d5
	cmp.b	$7FFF(a2),d5
	cmp.b	$7F(a2,d5.w),d5
	cmp.b	($FFFFFFFF).w,d5
	cmp.b	($FFFFFFFF).l,d5
	cmp.b	*(pc),d5
	cmp.b	*(pc,d5.w),d5
	cmp.w	d2,d5
	cmp.w	(a2),d5
	cmp.w	(a2)+,d5
	cmp.w	-(a2),d5
	cmp.w	$7FFF(a2),d5
	cmp.w	$7F(a2,d5.w),d5
	cmp.w	($FFFFFFFF).w,d5
	cmp.w	($FFFFFFFF).l,d5
	cmp.w	*(pc),d5
	cmp.w	*(pc,d5.w),d5
	cmp.l	d2,d5
	cmp.l	(a2),d5
	cmp.l	(a2)+,d5
	cmp.l	-(a2),d5
	cmp.l	$7FFF(a2),d5
	cmp.l	$7F(a2,d5.w),d5
	cmp.l	($FFFFFFFF).w,d5
	cmp.l	($FFFFFFFF).l,d5
	cmp.l	*(pc),d5
	cmp.l	*(pc,d5.w),d5

	cmpa.w	d5,a2
	cmpa.w	a5,a2
	cmpa.w	(a2),a2
	cmpa.w	(a2)+,a2
	cmpa.w	-(a2),a2
	cmpa.w	$7FFF(a2),a2
	cmpa.w	$7F(a2,d5.w),a2
	cmpa.w	($FFFFFFFF).w,a2
	cmpa.w	($FFFFFFFF).l,a2
	cmpa.w	#$FFFF,a2
	cmpa.w	*(pc),a2
	cmpa.w	*(pc,d5.w),a2
	cmpa.l	d5,a2
	cmpa.l	a5,a2
	cmpa.l	(a2),a2
	cmpa.l	(a2)+,a2
	cmpa.l	-(a2),a2
	cmpa.l	$7FFF(a2),a2
	cmpa.l	$7F(a2,d5.w),a2
	cmpa.l	($FFFFFFFF).w,a2
	cmpa.l	($FFFFFFFF).l,a2
	cmpa.l	#$FFFF,a2
	cmpa.l	*(pc),a2
	cmpa.l	*(pc,d5.w),a2

	mulu.w	d2,d5
	mulu.w	(a2),d5
	mulu.w	(a2)+,d5
	mulu.w	-(a2),d5
	mulu.w	$7FFF(a2),d5
	mulu.w	$7F(a2,d5.w),d5
	mulu.w	($FFFFFFFF).w,d5
	mulu.w	($FFFFFFFF).l,d5
	mulu.w	#$FFFF,d5
	mulu.w	*(pc),d5
	mulu.w	*(pc,d5.w),d5
	mulu	d2,d5
	mulu	(a2),d5
	mulu	(a2)+,d5
	mulu	-(a2),d5
	mulu	$7FFF(a2),d5
	mulu	$7F(a2,d5.w),d5
	mulu	($FFFFFFFF).w,d5
	mulu	($FFFFFFFF).l,d5
	mulu	#$FFFF,d5
	mulu	*(pc),d5
	mulu	*(pc,d5.w),d5

	muls.w	d2,d5
	muls.w	(a2),d5
	muls.w	(a2)+,d5
	muls.w	-(a2),d5
	muls.w	$7FFF(a2),d5
	muls.w	$7F(a2,d5.w),d5
	muls.w	($FFFFFFFF).w,d5
	muls.w	($FFFFFFFF).l,d5
	muls.w	#$FFFF,d5
	muls.w	*(pc),d5
	muls.w	*(pc,d5.w),d5
	muls	d2,d5
	muls	(a2),d5
	muls	(a2)+,d5
	muls	-(a2),d5
	muls	$7FFF(a2),d5
	muls	$7F(a2,d5.w),d5
	muls	($FFFFFFFF).w,d5
	muls	($FFFFFFFF).l,d5
	muls	#$FFFF,d5
	muls	*(pc),d5
	muls	*(pc,d5.w),d5

	abcd.b	d2,d5
	abcd.b	-(a2),-(a2)
	abcd	d2,d5
	abcd	-(a2),-(a2)

	exg.l	d2,d5
	exg.l	a5,a2
	exg.l	d5,a7
	exg.l	a7,d5
	exg	d2,d5
	exg	a5,a2
	exg	d5,a7
	exg	a7,d5

	and.b	d2,d5
	and.b	(a2),d5
	and.b	(a2)+,d5
	and.b	-(a2),d5
	and.b	$7FFF(a2),d5
	and.b	$7F(a2,d5.w),d5
	and.b	($FFFFFFFF).w,d5
	and.b	($FFFFFFFF).l,d5
	and.b	*(pc),d5
	and.b	*(pc,d5.w),d5
	and.b	d5,(a2)
	and.b	d5,(a2)+
	and.b	d5,-(a2)
	and.b	d5,$7FFF(a2)
	and.b	d5,$7F(a2,d5.w)
	and.b	d5,($FFFFFFFF).w
	and.b	d5,($FFFFFFFF).l
	and.w	d2,d5
	and.w	(a2),d5
	and.w	(a2)+,d5
	and.w	-(a2),d5
	and.w	$7FFF(a2),d5
	and.w	$7F(a2,d5.w),d5
	and.w	($FFFFFFFF).w,d5
	and.w	($FFFFFFFF).l,d5
	and.w	*(pc),d5
	and.w	*(pc,d5.w),d5
	and.w	d5,(a2)
	and.w	d5,(a2)+
	and.w	d5,-(a2)
	and.w	d5,$7FFF(a2)
	and.w	d5,$7F(a2,d5.w)
	and.w	d5,($FFFFFFFF).w
	and.w	d5,($FFFFFFFF).l
	and.l	d2,d5
	and.l	(a2),d5
	and.l	(a2)+,d5
	and.l	-(a2),d5
	and.l	$7FFF(a2),d5
	and.l	$7F(a2,d5.w),d5
	and.l	($FFFFFFFF).w,d5
	and.l	($FFFFFFFF).l,d5
	and.l	*(pc),d5
	and.l	*(pc,d5.w),d5
	and.l	d5,(a2)
	and.l	d5,(a2)+
	and.l	d5,-(a2)
	and.l	d5,$7FFF(a2)
	and.l	d5,$7F(a2,d5.w)
	and.l	d5,($FFFFFFFF).w
	and.l	d5,($FFFFFFFF).l

	add.b	d2,d5
	add.b	(a2),d5
	add.b	(a2)+,d5
	add.b	-(a2),d5
	add.b	$7FFF(a2),d5
	add.b	$7F(a2,d5.w),d5
	add.b	($FFFFFFFF).w,d5
	add.b	($FFFFFFFF).l,d5
	add.b	*(pc),d5
	add.b	*(pc,d5.w),d5
	add.b	d5,(a2)
	add.b	d5,(a2)+
	add.b	d5,-(a2)
	add.b	d5,$7FFF(a2)
	add.b	d5,$7F(a2,d5.w)
	add.b	d5,($FFFFFFFF).w
	add.b	d5,($FFFFFFFF).l
	add.w	d2,d5
	add.w	(a2),d5
	add.w	(a2)+,d5
	add.w	-(a2),d5
	add.w	$7FFF(a2),d5
	add.w	$7F(a2,d5.w),d5
	add.w	($FFFFFFFF).w,d5
	add.w	($FFFFFFFF).l,d5
	add.w	*(pc),d5
	add.w	*(pc,d5.w),d5
	add.w	d5,(a2)
	add.w	d5,(a2)+
	add.w	d5,-(a2)
	add.w	d5,$7FFF(a2)
	add.w	d5,$7F(a2,d5.w)
	add.w	d5,($FFFFFFFF).w
	add.w	d5,($FFFFFFFF).l
	add.l	d2,d5
	add.l	(a2),d5
	add.l	(a2)+,d5
	add.l	-(a2),d5
	add.l	$7FFF(a2),d5
	add.l	$7F(a2,d5.w),d5
	add.l	($FFFFFFFF).w,d5
	add.l	($FFFFFFFF).l,d5
	add.l	*(pc),d5
	add.l	*(pc,d5.w),d5
	add.l	d5,(a2)
	add.l	d5,(a2)+
	add.l	d5,-(a2)
	add.l	d5,$7FFF(a2)
	add.l	d5,$7F(a2,d5.w)
	add.l	d5,($FFFFFFFF).w
	add.l	d5,($FFFFFFFF).l

	addx.b	d2,d5
	addx.b	-(a2),-(a2)
	addx.w	d2,d5
	addx.w	-(a2),-(a2)
	addx.l	d2,d5
	addx.l	-(a2),-(a2)

	adda.w	d5,a2
	adda.w	a5,a2
	adda.w	(a2),a2
	adda.w	(a2)+,a2
	adda.w	-(a2),a2
	adda.w	$7FFF(a2),a2
	adda.w	$7F(a2,d5.w),a2
	adda.w	($FFFFFFFF).w,a2
	adda.w	($FFFFFFFF).l,a2
	adda.w	#$7FFF,a2
	adda.w	*(pc),a2
	adda.w	*(pc,d5.w),a2
	adda.l	d5,a2
	adda.l	a5,a2
	adda.l	(a2),a2
	adda.l	(a2)+,a2
	adda.l	-(a2),a2
	adda.l	$7FFF(a2),a2
	adda.l	$7F(a2,d5.w),a2
	adda.l	($FFFFFFFF).w,a2
	adda.l	($FFFFFFFF).l,a2
	adda.l	#$7FFF,a2
	adda.l	*(pc),a2
	adda.l	*(pc,d5.w),a2

	asl.b	d2,d5
	asl.b	#1,d5
	asl.w	d2,d5
	asl.w	#1,d5
	asl.l	d2,d5
	asl.l	#1,d5
	asl.w	(a2)
	asl.w	(a2)+
	asl.w	-(a2)
	asl.w	$7FFF(a2)
	asl.w	$7F(a2,d5.w)
	asl.w	($FFFFFFFF).w
	asl.w	($FFFFFFFF).l
	asl	(a2)
	asl	(a2)+
	asl	-(a2)
	asl	$7FFF(a2)
	asl	$7F(a2,d5.w)
	asl	($FFFFFFFF).w
	asl	($FFFFFFFF).l

	asr.b	d2,d5
	asr.b	#1,d5
	asr.w	d2,d5
	asr.w	#1,d5
	asr.l	d2,d5
	asr.l	#1,d5
	asr.w	(a2)
	asr.w	(a2)+
	asr.w	-(a2)
	asr.w	$7FFF(a2)
	asr.w	$7F(a2,d5.w)
	asr.w	($FFFFFFFF).w
	asr.w	($FFFFFFFF).l
	asr	(a2)
	asr	(a2)+
	asr	-(a2)
	asr	$7FFF(a2)
	asr	$7F(a2,d5.w)
	asr	($FFFFFFFF).w
	asr	($FFFFFFFF).l

	lsl.b	d2,d5
	lsl.b	#1,d5
	lsl.w	d2,d5
	lsl.w	#1,d5
	lsl.l	d2,d5
	lsl.l	#1,d5
	lsl.w	(a2)
	lsl.w	(a2)+
	lsl.w	-(a2)
	lsl.w	$7FFF(a2)
	lsl.w	$7F(a2,d5.w)
	lsl.w	($FFFFFFFF).w
	lsl.w	($FFFFFFFF).l
	lsl	(a2)
	lsl	(a2)+
	lsl	-(a2)
	lsl	$7FFF(a2)
	lsl	$7F(a2,d5.w)
	lsl	($FFFFFFFF).w
	lsl	($FFFFFFFF).l

	lsr.b	d2,d5
	lsr.b	#1,d5
	lsr.w	d2,d5
	lsr.w	#1,d5
	lsr.l	d2,d5
	lsr.l	#1,d5
	lsr.w	(a2)
	lsr.w	(a2)+
	lsr.w	-(a2)
	lsr.w	$7FFF(a2)
	lsr.w	$7F(a2,d5.w)
	lsr.w	($FFFFFFFF).w
	lsr.w	($FFFFFFFF).l
	lsr	(a2)
	lsr	(a2)+
	lsr	-(a2)
	lsr	$7FFF(a2)
	lsr	$7F(a2,d5.w)
	lsr	($FFFFFFFF).w
	lsr	($FFFFFFFF).l

	roxl.b	d2,d5
	roxl.b	#1,d5
	roxl.w	d2,d5
	roxl.w	#1,d5
	roxl.l	d2,d5
	roxl.l	#1,d5
	roxl.w	(a2)
	roxl.w	(a2)+
	roxl.w	-(a2)
	roxl.w	$7FFF(a2)
	roxl.w	$7F(a2,d5.w)
	roxl.w	($FFFFFFFF).w
	roxl.w	($FFFFFFFF).l
	roxl	(a2)
	roxl	(a2)+
	roxl	-(a2)
	roxl	$7FFF(a2)
	roxl	$7F(a2,d5.w)
	roxl	($FFFFFFFF).w
	roxl	($FFFFFFFF).l

	roxr.b	d2,d5
	roxr.b	#1,d5
	roxr.w	d2,d5
	roxr.w	#1,d5
	roxr.l	d2,d5
	roxr.l	#1,d5
	roxr.w	(a2)
	roxr.w	(a2)+
	roxr.w	-(a2)
	roxr.w	$7FFF(a2)
	roxr.w	$7F(a2,d5.w)
	roxr.w	($FFFFFFFF).w
	roxr.w	($FFFFFFFF).l
	roxr	(a2)
	roxr	(a2)+
	roxr	-(a2)
	roxr	$7FFF(a2)
	roxr	$7F(a2,d5.w)
	roxr	($FFFFFFFF).w
	roxr	($FFFFFFFF).l

	rol.b	d2,d5
	rol.b	#1,d5
	rol.w	d2,d5
	rol.w	#1,d5
	rol.l	d2,d5
	rol.l	#1,d5
	rol.w	(a2)
	rol.w	(a2)+
	rol.w	-(a2)
	rol.w	$7FFF(a2)
	rol.w	$7F(a2,d5.w)
	rol.w	($FFFFFFFF).w
	rol.w	($FFFFFFFF).l
	rol	(a2)
	rol	(a2)+
	rol	-(a2)
	rol	$7FFF(a2)
	rol	$7F(a2,d5.w)
	rol	($FFFFFFFF).w
	rol	($FFFFFFFF).l

	ror.b	d2,d5
	ror.b	#1,d5
	ror.w	d2,d5
	ror.w	#1,d5
	ror.l	d2,d5
	ror.l	#1,d5
	ror.w	(a2)
	ror.w	(a2)+
	ror.w	-(a2)
	ror.w	$7FFF(a2)
	ror.w	$7F(a2,d5.w)
	ror.w	($FFFFFFFF).w
	ror.w	($FFFFFFFF).l
	ror	(a2)
	ror	(a2)+
	ror	-(a2)
	ror	$7FFF(a2)
	ror	$7F(a2,d5.w)
	ror	($FFFFFFFF).w
	ror	($FFFFFFFF).l
